# Generated by Django 4.0.6 on 2022-08-18 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('1', 'Şoför'), ('2', 'Admin'), ('3', 'Saha Operasyon')], default='1', max_length=1)),
                ('PackageId', models.CharField(default='', max_length=50, verbose_name='PackageId')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IYS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='0', max_length=50)),
                ('message_permission_by_phone', models.BooleanField(default=False)),
                ('message_permission_by_phone_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message_permission_by_email', models.BooleanField(default=False)),
                ('message_permission_by_email_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message_permission_by_sms', models.BooleanField(default=False)),
                ('message_permission_by_sms_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=5, max_length=50, validators=[django.core.validators.MaxValueValidator(300.0)])),
                ('OrderID', models.CharField(default='', max_length=50)),
                ('CurrencyCode', models.CharField(default='', max_length=50)),
                ('TransactionType', models.CharField(choices=[('Sale', 'Sale'), ('Void', 'Void'), ('Refund', 'Refund')], default='Sale', max_length=50)),
                ('CallBackURL', models.CharField(blank=True, default='', max_length=50)),
                ('AdditionalAmount', models.DecimalField(decimal_places=2, default='0.00', max_digits=5, validators=[django.core.validators.MaxValueValidator(300.0)], verbose_name='Hizmet Bedeli')),
                ('Caption', models.CharField(blank=True, default='Hizmet Bedeli', max_length=50)),
                ('IntegrationKey', models.CharField(blank=True, default='Key', max_length=50)),
                ('UserHash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='OtpPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=50, verbose_name='OTP Şifresi')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='iys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.iys', verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
