# Generated by Django 4.0.7 on 2022-08-21 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PackageId',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='PackageId'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
