# Generated by Django 4.0.7 on 2022-08-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_packageid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otppassword',
            old_name='password',
            new_name='verification_code',
        ),
    ]
