# Generated by Django 4.0.7 on 2022-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posauthorize_serverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('200', '200'), ('300', '300')], default='200', max_length=50),
        ),
    ]
