# Generated by Django 4.0.7 on 2022-09-25 21:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serverstatus_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsession',
            name='AdditionalAmount',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='Caption',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='IntegrationKey',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='otppassword',
            name='verification_code',
            field=models.CharField(max_length=50, verbose_name='OTP Şifresi'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=50, validators=[django.core.validators.MaxValueValidator(Decimal('300.00'))], verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='CallBackURL',
            field=models.CharField(blank=True, default='https://www.provision.com/receipt', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='CurrencyCode',
            field=models.CharField(blank=True, default='TRY', max_length=5),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='OrderID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='TransactionType',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Void', 'Void'), ('Refund', 'Refund')], default='Sale', max_length=10),
        ),
        migrations.CreateModel(
            name='AdditionalAmounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('12.25'), max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('300.00'))], verbose_name='Hizmet Bedeli')),
                ('Caption', models.CharField(blank=True, default='Hizmet Bedeli', max_length=50)),
                ('IntegrationKey', models.CharField(blank=True, default='Key', max_length=50)),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentsession', verbose_name='İlgili Payment Session')),
            ],
        ),
    ]
