# Generated by Django 4.0.7 on 2022-09-26 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_paymentsession_additionalamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStarted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentSessionToken', models.CharField(max_length=16, verbose_name='PaymentSessionToken')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentsession', verbose_name='İlgili Payment Session')),
            ],
        ),
    ]
