# Generated by Django 4.0.7 on 2022-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_paymentstarted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='PackageId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_enrolled',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Inactive'), ('3', 'Passive'), ('4', 'Pending')], default='4', max_length=1),
        ),
    ]
