# Generated by Django 4.0.7 on 2022-10-09 23:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_customuser_packageid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, max_length=50, verbose_name='Bakiye'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clarification_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clarification_text_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fastpay_phone',
            field=models.CharField(default='', max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kvkk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kvkk_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plate_number',
            field=models.CharField(blank=True, default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50, validators=[django.core.validators.MaxValueValidator(Decimal('300.00'))], verbose_name='Tutar'),
        ),
    ]
