# Generated by Django 4.0.7 on 2022-10-10 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customuser_balance_customuser_clarification_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fastpay_phone',
            field=models.CharField(blank=True, default='', max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
