# Generated by Django 4.0.7 on 2022-10-10 18:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_fastpay_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalamounts',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('12.25'), max_digits=5, verbose_name='Hizmet Bedeli'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50, verbose_name='Tutar'),
        ),
    ]
