# Generated by Django 4.0.7 on 2022-10-12 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_additionalamounts_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tckn',
            field=models.CharField(default='11111111111', max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='TC No'),
        ),
        migrations.AddField(
            model_name='iys',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon'),
        ),
    ]
