# Generated by Django 4.0.7 on 2022-10-12 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_tckn_iys_phone_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='99999999999', max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon')),
                ('plate_0', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_1', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_2', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_3', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_4', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_5', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_6', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_7', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_8', models.CharField(blank=True, max_length=8, null=True)),
                ('plate_9', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='clarification_text',
            new_name='aydinlatma',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='clarification_text_timestamp',
            new_name='aydinlatma_timestamp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plate_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='vehicles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicles', verbose_name='Kullanıcı'),
        ),
    ]
