# Generated by Django 4.0.7 on 2022-10-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_vehicles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.iys', verbose_name='IYS'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vehicles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicles', verbose_name='Araçlar'),
        ),
    ]
