# Generated by Django 4.0.7 on 2022-10-14 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_customuser_iys_alter_customuser_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
        ),
    ]
