# Generated by Django 4.0.7 on 2022-10-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_customuser_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='vehicles',
            new_name='plate_numbers',
        ),
    ]
