# Generated by Django 4.0.7 on 2022-10-22 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_vehicles_customuser_plate_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRemote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, default='', verbose_name='Webhook Data')),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
