# Generated by Django 4.0.7 on 2022-11-04 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_webhookremote_payment_session_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deeplink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('PaymentSessionToken', models.CharField(max_length=16, verbose_name='PaymentSessionToken')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('Approved', models.BooleanField(blank=True, null=True, verbose_name='Onaylandı')),
            ],
        ),
        migrations.RemoveField(
            model_name='otppassword',
            name='created',
        ),
        migrations.RemoveField(
            model_name='paymentsession',
            name='CallBackURL',
        ),
        migrations.RemoveField(
            model_name='posauthorize',
            name='created',
        ),
        migrations.RemoveField(
            model_name='serverstatus',
            name='created_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='calisma_ruhsat_no',
            field=models.CharField(default='111111', max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Çalışma Ruhsat No'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sozlesme_no',
            field=models.CharField(default='11111111', max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Sözleşme No'),
        ),
        migrations.AddField(
            model_name='otppassword',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='posauthorize',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='posauthorize',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='additionalamounts',
            name='payment_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentsession', verbose_name='Payment Session'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='aydinlatma_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Aydınlatma Timestamp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kvkk_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='KVKK Timestamp'),
        ),
        migrations.AlterField(
            model_name='iys',
            name='message_permission_by_email',
            field=models.BooleanField(default=False, verbose_name='E-posta İzni'),
        ),
        migrations.AlterField(
            model_name='iys',
            name='message_permission_by_phone',
            field=models.BooleanField(default=False, verbose_name='Telefon İzni'),
        ),
        migrations.AlterField(
            model_name='iys',
            name='message_permission_by_sms',
            field=models.BooleanField(default=False, verbose_name='Sms İzni'),
        ),
        migrations.AlterField(
            model_name='posauthorize',
            name='Token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='message',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('200', '200'), ('300', '300')], default='200', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Versiyon'),
        ),
        migrations.AlterField(
            model_name='webhookremote',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Webhook Data'),
        ),
        migrations.AlterField(
            model_name='webhookremote',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.DeleteModel(
            name='PaymentStarted',
        ),
        migrations.AddField(
            model_name='deeplink',
            name='payment_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentsession', verbose_name='İlgili Payment Session'),
        ),
    ]
