# Generated by Django 4.0.7 on 2022-11-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_deeplink_remove_otppassword_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Onay Kodu')),
                ('seller', models.CharField(blank=True, default='Sarı Teknoloji', max_length=50, verbose_name='Alıcı')),
                ('DriverAmount', models.DecimalField(blank=True, decimal_places=2, default=12.25, max_digits=5, verbose_name='Taksimetre Tutarı')),
                ('AdditionalAmount', models.DecimalField(blank=True, decimal_places=2, default=12.25, max_digits=5, verbose_name='İşlem Ücreti')),
                ('TransactionDate', models.CharField(blank=True, default='', max_length=25, verbose_name='TransactionDate')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Bakiye'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('200', '200'), ('300', '300')], default='200', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='version',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Versiyon'),
        ),
        migrations.CreateModel(
            name='MobileTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(blank=True, default='', max_length=25, verbose_name='TransactionDate')),
                ('TransactionDate', models.CharField(blank=True, default='', max_length=25, verbose_name='TransactionDate')),
                ('DriverAmount', models.DecimalField(blank=True, decimal_places=2, default=12.25, max_digits=5, verbose_name='Taksimetre Tutarı')),
                ('IsVoidable', models.BooleanField(blank=True, null=True, verbose_name='IsVoidable')),
                ('IsRefundable', models.BooleanField(blank=True, null=True, verbose_name='IsRefundable')),
                ('QRLink', models.URLField(blank=True, default='https://banapos.com', null=True, verbose_name='QRLink')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.receipt', verbose_name='Receipt')),
            ],
        ),
    ]
