# Generated by Django 4.0.7 on 2022-11-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_receipt_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='ref_no',
            new_name='approval_code',
        ),
    ]
