# Generated by Django 4.0.7 on 2022-11-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_ref_no_receipt_approval_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deeplink',
            name='PaymentSessionToken',
        ),
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='deeplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deeplink', verbose_name='İlgili Deeplink'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='PaymentSessionToken',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='PaymentSessionToken'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='DriverAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taksimetre Tutarı'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='OrderId',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='OrderId'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='DriverAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taksimetre Tutarı'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='seller',
            field=models.CharField(blank=True, default='Sarı Teknoloji', max_length=25, verbose_name='Alıcı'),
        ),
    ]
