# Generated by Django 4.0.7 on 2022-11-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_deeplink_paymentsessiontoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='OrderId',
            field=models.UUIDField(blank=True, default='', verbose_name='OrderId'),
        ),
    ]
