# Generated by Django 4.0.7 on 2022-11-09 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_mobiletransactionhistory_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, max_length=50, verbose_name='Bakiye')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
            ],
        ),
        migrations.AlterField(
            model_name='additionalamounts',
            name='Caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
