# Generated by Django 4.0.7 on 2022-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_balanceinfo_alter_additionalamounts_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceInfo',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='approval_code',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='seller',
        ),
        migrations.AddField(
            model_name='receipt',
            name='AID',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='AID'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ApplicationLabel',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='ApplicationLabel'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='AuthorizationCode',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='AuthorizationCode'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='CardNumber',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='CardNumber'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='MerchantID',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='MerchantID'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='Message',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='OperationName',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='OperationName'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='RRN',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='RRN'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='Response',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='Status',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='TerminalID',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='TerminalID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='AdditionalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='İşlem Ücreti'),
        ),
    ]
