# Generated by Django 4.0.7 on 2022-11-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_delete_balanceinfo_remove_receipt_approval_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='success',
            field=models.BooleanField(blank=True, null=True, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='additionalamounts',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Hizmet Bedeli'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='DriverAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taksimetre Tutarı'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='DriverAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taksimetre Tutarı'),
        ),
    ]
