# Generated by Django 4.0.7 on 2022-11-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_mobiletransactionhistory_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Toplam Tutar'),
        ),
    ]
