# Generated by Django 4.0.7 on 2022-11-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_customuser_name_alter_customuser_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, default='', max_length=15, verbose_name='lat')),
                ('lon', models.CharField(blank=True, default='', max_length=15, verbose_name='lon')),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentsession', verbose_name='Payment Session')),
            ],
        ),
    ]
