# Generated by Django 4.0.7 on 2022-11-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_paymentlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiletransactionhistory',
            name='OrderId',
        ),
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='OrderID',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
    ]
