# Generated by Django 4.0.7 on 2022-11-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_deeplink_isrefundable_deeplink_isvoidable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ApplicationLabel',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='ApplicationLabel'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='MerchantID',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='MerchantID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='Message',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='TerminalID',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='TerminalID'),
        ),
    ]
