# Generated by Django 4.0.7 on 2022-11-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_receipt_applicationlabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_used'),
        ),
    ]
