# Generated by Django 4.0.7 on 2022-11-23 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_paymentsession_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAuthorize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
            ],
        ),
        migrations.RemoveField(
            model_name='posauthorize',
            name='access_token',
        ),
    ]
