# Generated by Django 4.0.7 on 2022-11-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_customuser_fastpay_phone_otppassword_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='deeplink',
            name='Status',
            field=models.CharField(blank=True, default='3', max_length=2),
        ),
    ]
