# Generated by Django 4.0.7 on 2022-11-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_deeplink_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='plate_0',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_1',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_2',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_3',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_4',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_5',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_6',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_7',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_8',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='plate_9',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
