# Generated by Django 4.0.7 on 2022-11-25 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_vehicles_plate_0_alter_vehicles_plate_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iys',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sozlesme_no',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Sözleşme No'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tckn',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='TC No'),
        ),
        migrations.AlterField(
            model_name='iys',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon'),
        ),
    ]
