# Generated by Django 4.0.7 on 2022-11-26 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_iys_user_id_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalamounts',
            options={'verbose_name_plural': 'Additional amounts'},
        ),
        migrations.AlterModelOptions(
            name='iys',
            options={'verbose_name_plural': 'IYS'},
        ),
        migrations.AlterModelOptions(
            name='mobiletransactionhistory',
            options={'verbose_name_plural': 'Mobile Transaction Histories'},
        ),
        migrations.AlterModelOptions(
            name='serverstatus',
            options={'verbose_name_plural': 'Server statuses'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Telefon'),
        ),
    ]
