# Generated by Django 4.0.7 on 2022-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_additionalamounts_options_alter_iys_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='qr_id',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='QR ID'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='QRLink',
            field=models.URLField(blank=True, default='https://banapos.com', verbose_name='QRLink'),
        ),
    ]
