# Generated by Django 4.0.7 on 2022-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_mobiletransactionhistory_qr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='TransactionType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
