# Generated by Django 4.0.7 on 2022-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_dailybalanceinfo_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calisma_ruhsat_no',
            field=models.CharField(default='111111', max_length=6, verbose_name='Çalışma Ruhsat No'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sozlesme_no',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Sözleşme No'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tckn',
            field=models.CharField(default='11111111111', max_length=11, verbose_name='TC No'),
        ),
        migrations.AlterField(
            model_name='dailybalanceinfo',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='dailybalanceinfo',
            name='tckn',
            field=models.CharField(default='11111111111', max_length=11, verbose_name='TC No'),
        ),
        migrations.AlterField(
            model_name='iys',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, verbose_name='Telefon'),
        ),
    ]
