# Generated by Django 4.0.7 on 2022-12-09 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_customuser_calisma_ruhsat_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.TextField(blank=True, default='')),
                ('key', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
