# Generated by Django 4.0.7 on 2022-12-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_endofday_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plate_numbers',
        ),
    ]
