# Generated by Django 4.0.7 on 2022-12-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_vehicles_phone_remove_vehicles_plate_0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='vehicles',
            field=models.ManyToManyField(to='api.vehicles'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='QRLink',
            field=models.URLField(blank=True, default='https://banapos.com/qr/', verbose_name='QRLink'),
        ),
    ]
