# Generated by Django 4.0.7 on 2022-12-20 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_deeplink_hashdata_alter_endofday_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('Approved', models.BooleanField(blank=True, null=True, verbose_name='Onaylandı')),
                ('IsVoidable', models.BooleanField(blank=True, null=True, verbose_name='IsVoidable')),
                ('IsRefundable', models.BooleanField(blank=True, null=True, verbose_name='IsRefundable')),
                ('Status', models.CharField(blank=True, default='', max_length=2)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('TransactionType', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Void', 'Void'), ('Refund', 'Refund')], default='Sale', max_length=10)),
                ('hashData', models.TextField(blank=True, default='', verbose_name='hashData')),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentsession', verbose_name='İlgili Payment Session')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantID', models.CharField(blank=True, default='', max_length=20, verbose_name='MerchantID')),
                ('TerminalID', models.CharField(blank=True, default='', max_length=20, verbose_name='TerminalID')),
                ('CardNumber', models.CharField(blank=True, default='', max_length=16, verbose_name='CardNumber')),
                ('AuthorizationCode', models.CharField(blank=True, default='', max_length=16, verbose_name='AuthorizationCode')),
                ('OperationName', models.CharField(blank=True, default='', max_length=16, verbose_name='OperationName')),
                ('Status', models.CharField(blank=True, default='', max_length=16, verbose_name='Status')),
                ('Response', models.CharField(blank=True, default='', max_length=16, verbose_name='Response')),
                ('Message', models.CharField(blank=True, default='', max_length=50, verbose_name='Message')),
                ('RRN', models.CharField(blank=True, default='', max_length=16, verbose_name='RRN')),
                ('ApplicationLabel', models.CharField(blank=True, default='', max_length=25, verbose_name='ApplicationLabel')),
                ('AID', models.CharField(blank=True, default='', max_length=16, verbose_name='AID')),
                ('DriverAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taksimetre Tutarı')),
                ('AdditionalAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='İşlem Ücreti')),
                ('TransactionDate', models.CharField(blank=True, default='', max_length=25, verbose_name='TransactionDate')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='99999999999', max_length=11, verbose_name='Telefon')),
                ('OrderID', models.CharField(blank=True, default='', editable=False, max_length=40)),
                ('success', models.BooleanField(blank=True, null=True, verbose_name='Success')),
                ('TransactionDate', models.CharField(blank=True, default='', max_length=25, verbose_name='TransactionDate')),
                ('DriverAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Taksimetre Tutarı')),
                ('IsVoidable', models.BooleanField(blank=True, null=True, verbose_name='IsVoidable')),
                ('IsRefundable', models.BooleanField(blank=True, null=True, verbose_name='IsRefundable')),
                ('QRLink', models.URLField(blank=True, default='https://banapos.com/qr/?', verbose_name='QRLink')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('TransactionType', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhookreceipt', verbose_name='Receipt')),
                ('webhook_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhookdata', verbose_name='İlgili Deeplink')),
            ],
            options={
                'verbose_name_plural': 'Mobile Transaction Histories',
            },
        ),
        migrations.DeleteModel(
            name='WebhookRemote',
        ),
        migrations.AlterField(
            model_name='deeplink',
            name='Status',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='deeplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deeplink', verbose_name='Webhook Data'),
        ),
    ]
