# Generated by Django 4.0.7 on 2022-12-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_webhookdata_webhookreceipt_webhooktransactionhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransactionhistory',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhookreceipt', verbose_name='Webhook Receipt'),
        ),
    ]
