# Generated by Django 4.0.7 on 2022-12-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_webhooktransactionhistory_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhooktransactionhistory',
            options={'verbose_name_plural': 'Webhook Transaction Histories'},
        ),
    ]
