# Generated by Django 4.0.7 on 2022-12-22 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_customuser_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='deeplink',
            name='void_refund_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.voidrefundsession', verbose_name='İlgili Void Session'),
        ),
        migrations.AddField(
            model_name='voidrefundsession',
            name='PaymentSessionToken',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='PaymentSessionToken'),
        ),
        migrations.AddField(
            model_name='voidrefundsession',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_used'),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='void_refund_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.voidrefundsession', verbose_name='İlgili Void Session'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='OrderID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voidrefundsession',
            name='OrderID',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
