# Generated by Django 4.0.7 on 2022-12-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_deeplink_void_refund_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdata',
            name='Status',
        ),
    ]
