# Generated by Django 4.0.7 on 2023-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_webhookdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='receipt',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='phone',
            field=models.CharField(blank=True, default='99999999999', max_length=11, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='voidrefundsession',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='webhookreceipt',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='webhooktransactionhistory',
            name='plate',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
