# Generated by Django 4.0.7 on 2023-01-07 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_mobiletransactionhistory_plate_paymentsession_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='is_available',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='picked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Aracı Alma Zamanı'),
        ),
    ]
