# Generated by Django 4.0.7 on 2023-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_vehicles_is_available_vehicles_picked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='picked_at',
            field=models.DateTimeField(verbose_name='Aracı Alma Zamanı'),
        ),
    ]
