# Generated by Django 4.0.7 on 2023-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_vehicles_picked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='picked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aracı Alma Zamanı'),
        ),
    ]
