# Generated by Django 4.0.7 on 2023-01-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_customuser_vehicles'),
        ('api', '0062_alter_vehicles_picked_at'),
    ]

    operations = [
    ]
