# Generated by Django 4.0.7 on 2023-01-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20230113_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlocation',
            name='void_refund_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.voidrefundsession', verbose_name='İlgili Void Session'),
        ),
    ]
