# Generated by Django 4.0.7 on 2023-01-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_paymentlocation_void_refund_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransactionhistory',
            name='webhook_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhookdata', verbose_name='Webhook Data'),
        ),
    ]
