# Generated by Django 4.0.7 on 2023-01-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_webhooktransactionhistory_webhook_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Bakiye'),
        ),
        migrations.AlterField(
            model_name='dailybalanceinfo',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, max_length=50, verbose_name='Bakiye'),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='DriverAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Taksimetre Tutarı'),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='DriverAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Taksimetre Tutarı'),
        ),
        migrations.AlterField(
            model_name='webhookreceipt',
            name='DriverAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Taksimetre Tutarı'),
        ),
        migrations.AlterField(
            model_name='webhooktransactionhistory',
            name='DriverAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Taksimetre Tutarı'),
        ),
    ]
