# Generated by Django 4.0.7 on 2023-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='webhooktransactionhistory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='webhooktransactionhistory',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
