# Generated by Django 4.0.7 on 2023-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_mobiletransactionhistory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='TransactionDate',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='TransactionDate'),
        ),
    ]
