# Generated by Django 4.0.7 on 2023-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_mobiletransactionhistory_transactiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalamounts',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Hizmet Bedeli'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='AdditionalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='İşlem Ücreti'),
        ),
        migrations.AlterField(
            model_name='webhookreceipt',
            name='AdditionalAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='İşlem Ücreti'),
        ),
    ]
