# Generated by Django 4.0.7 on 2023-02-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_additionalamounts_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktransactionhistory',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='webhooktransactionhistory',
            name='webhook_data',
        ),
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='ProcessType',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mobiletransactionhistory',
            name='webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.webhookdata', verbose_name='Webhook Data'),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='Status',
            field=models.CharField(blank=True, default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='mobiletransactionhistory',
            name='deeplink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deeplink', verbose_name='Deeplink Data'),
        ),
        migrations.DeleteModel(
            name='WebhookReceipt',
        ),
        migrations.DeleteModel(
            name='WebhookTransactionHistory',
        ),
    ]
