# Generated by Django 4.0.7 on 2023-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_webhooktransactionhistory_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='OrderID',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
    ]
