# Generated by Django 4.0.7 on 2023-03-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_receipt_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='version',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Versiyon'),
        ),
    ]
