# Generated by Django 4.0.7 on 2023-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_serverstatus_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='version',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Versiyon'),
        ),
    ]
